# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: ar

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Beirut

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: "أحمد الخطيب"

tagline: "مدونة أحمد الخطيب"

description: >- # used by seo meta and the atom feed
  سياسة، مجتمع، تكنولوجيا، برمجة، ذكاء اصطناعي

default_image: "/assets/img/ahmad-al-khatib-banner.webp"

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://website-4jv.pages.dev"
baseurl: "/blog"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at

github:
  username: AhmadAl-Khatib

twitter:
  username: alkhatib_ahmad1

social:
  name: أحمد الخطيب
  email: ahmad@ahmad-khatib.com
  links:
    - https://github.com/AhmadAl-Khatib
    - https://www.linkedin.com/in/alkhatibahmad/
    - https://twitter.com/alkhatib_ahmad1
    - https://www.facebook.com/ahmad.khatib.9237244
    - https://www.instagram.com/alkhatib_ahmad1/
    - https://www.youtube.com/@alkhatib_ahmad1
    - https://www.tiktok.com/@alkhatib_ahmad1
    - https://www.snapchat.com/add/alkhatib_ahmad1
    - https://www.amazon.com/author/ahmadalkhatib/
    - https://www.goodreads.com/author/show/981744.Ahmad_Al_Khatib/
# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: G-G7S1W78Z5J 

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode:

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: "/assets/img/ahmad-al-khatib-profile-picture.webp"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: "/assets/img/ahmad-al-khatib-banner.webp"

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: true # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: production

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
      image: "assets/img/ahmad-al-khatib-banner.webp"
      author: "أحمد الخطيب"
      lang: "ar"

  - scope:
      path: ""
      type: pages
    values:
      lang: "ar"

  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# ---------------- CUSTOM VARIABLES (safe extension) ----------------

logo: "/assets/img/ahmad-al-khatib-logo.png"

schema:
  person:
    job_title: "كاتب رأي ومؤلف، ناشط اجتماعي وسياسي، ورائد أعمال"
  image:
    width: 1200
    height: 630
  breadcrumb:
    home_name: "الرئيسية"     # homepage label
    blog_name: "المدونة"      # blog main page label
  person_id: "https://ahmad-khatib.com/#person"
  website_id: "https://ahmad-khatib.com/#website"
  content_location: "Lebanon"
  default_image: "/assets/img/ahmad-al-khatib-banner.webp"
  publisher_name: "أحمد الخطيب"
  url: "https://ahmad-khatib.com"
include:
  - assets/js/dist

seo:
  json_ld: false
