name: Build and Deploy Blog

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: blog-deploy
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Set up Node and build Chirpy assets
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm ci

      - name: Build Chirpy JS/CSS
        run: npm run build

      - name: Fail if JS bundle missing
        run: |
          if [ ! -d "assets/js/dist" ] || [ -z "$(ls -A assets/js/dist)" ]; then
            echo "❌ JS bundle missing in assets/js/dist"
            exit 1
          fi
          echo "✅ JS bundle found:"
          ls -la assets/js/dist

      # 3) Set up Ruby and build Jekyll site
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Build Jekyll site (production)
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --destination ./_site --trace --verbose

      # 4) Push built site to main website repo under /blog
      - name: Push _site to main website repo
        env:
          REPO: AhmadAl-Khatib/website
          BRANCH: main
          TOKEN: ${{ secrets.PERSONAL }}
        run: |
          set -euo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${TOKEN}@github.com/${REPO} temp-main
          mkdir -p temp-main/blog
          rsync -a --delete _site/ temp-main/blog/

          cd temp-main
          git add blog -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(blog): update blog HTML from blog-fac ${GITHUB_SHA::7}"
          git push origin ${BRANCH}
